name: scrapers

on:
  schedule:
    - cron: '30 10 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@2.2.1
        with:
          python-version: '3.8'
      - name: Run scraper
        run: python vaccine.py
