on:
  schedule: 
    - cron: "02 17 * * *" # EST is UTC - 5


jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
      - uses: actions/setup-python@v2.2.0
        with:
          python-version: 3.8
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Vaccine
        run: python3 vaccine.py
      - name: Ontario
        run: python3 ontario.py
      - name: London
        run: python3 london.py
      
      - name: Update
        run: |
          git add -A
          timestamp=$(date -u)
          git commit -m "Data update: ${timestamp}"
          git push
        
