name: Scraping

on:
  schedule:
  - cron: "02 17 * * *" # EST is UTC-5
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults: # setting to python dir
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Scrape vaccine
      run: python vaccine.py
    - name: Scrape Ontario
      run: python ontario.py
    - name: Scrape London
      run: python london.py
